apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: custom job with env

on:
  workflow_dispatch:

jobs:
  custom:
    delegates: mluzcabrera/customjobpoll/topollillo.yaml
    environment: environment_mlcb
    timeout-minutes: 4320
