apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: just manual approval
on:
  workflow_dispatch:
  workflow_call:
jobs:
  manual-approval:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: 7f5b8e40-03d4-11eb-9d67-42010a83ae35
      disallowLaunchByUser: false
      instructions: "click me"
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - manual-approval

