apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
jobs:
  custom:
    delegates: mluzcabrera/customjobpoll/topollillo.yaml
    timeout-minutes: 60
  build:
    needs: custom
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world ${{ needs.custom.outputs.result }}"
