apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Reusable workflow
on:
  workflow_dispatch:
jobs:
  runanother:
    environment: requires-approval
    needs: build
    uses: robkozura/approval-test/.cloudbees/workflows/longlastingworkflow.yaml
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
